apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  labels:
    app: test1
  namespace: namespace-workflow-1678733565890
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: test1
          image: acrworkflow1678733565890.azurecr.io/image-workflow-1678733565890:latest
          ports:
            - containerPort: 80